// ─── Open Trivia Database API ────────────────────────────────────────────────
// Free, no auth required. 4000+ questions across categories.

export interface TriviaQuestion {
  id: string;
  category: string;
  type: 'multiple' | 'boolean';
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  correct_answer: string;
  answers: string[]; // shuffled, includes correct
}

interface OTDBResponse {
  response_code: number;
  results: Array<{
    category: string;
    type: string;
    difficulty: string;
    question: string;
    correct_answer: string;
    incorrect_answers: string[];
  }>;
}

function decodeHTML(html: string): string {
  return html
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#039;/g, "'")
    .replace(/&ldquo;/g, '"')
    .replace(/&rdquo;/g, '"')
    .replace(/&hellip;/g, '…')
    .replace(/&eacute;/g, 'é')
    .replace(/&ndash;/g, '–')
    .replace(/&mdash;/g, '—');
}

function shuffleArray<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// Map category IDs to OTDB API numbers
const CATEGORY_MAP: Record<string, number> = {
  mixed: 0,
  science: 17,
  history: 23,
  tech: 18,
  sports: 21,
  pop: 11,
  geography: 22,
};

// Fallback questions if API fails (C3 expanded to 30+)
const FALLBACK_QUESTIONS: TriviaQuestion[] = [
  // ── Science ───────────────────────────────────────────────────────────
  { id: 'f-sc-1', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'What planet is known as the Red Planet?',
    correct_answer: 'Mars',
    answers: ['Mars', 'Venus', 'Jupiter', 'Mercury'] },
  { id: 'f-sc-2', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'What is the chemical symbol for Gold?',
    correct_answer: 'Au',
    answers: ['Au', 'Ag', 'Gd', 'Go'] },
  { id: 'f-sc-3', category: 'Science', type: 'multiple', difficulty: 'hard',
    question: 'How many bones are in the adult human body?',
    correct_answer: '206',
    answers: ['206', '208', '198', '212'] },
  { id: 'f-sc-4', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'Which gas do plants absorb from the atmosphere?',
    correct_answer: 'Carbon dioxide',
    answers: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'] },
  { id: 'f-sc-5', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'What is the speed of light in a vacuum (approximately)?',
    correct_answer: '300,000 km/s',
    answers: ['300,000 km/s', '150,000 km/s', '1,000,000 km/s', '3,000 km/s'] },
  { id: 'f-sc-6', category: 'Science', type: 'multiple', difficulty: 'hard',
    question: 'Who proposed the theory of general relativity?',
    correct_answer: 'Albert Einstein',
    answers: ['Albert Einstein', 'Isaac Newton', 'Niels Bohr', 'Stephen Hawking'] },

  // ── Technology ────────────────────────────────────────────────────────
  { id: 'f-tc-1', category: 'Technology', type: 'multiple', difficulty: 'easy',
    question: 'What does "HTML" stand for?',
    correct_answer: 'HyperText Markup Language',
    answers: ['HyperText Markup Language', 'Home Tool Markup Language', 'Hyper Transfer Markup Language', 'HyperText Management Language'] },
  { id: 'f-tc-2', category: 'Technology', type: 'multiple', difficulty: 'medium',
    question: 'Who is the co-founder of Microsoft?',
    correct_answer: 'Bill Gates',
    answers: ['Bill Gates', 'Steve Jobs', 'Mark Zuckerberg', 'Elon Musk'] },
  { id: 'f-tc-3', category: 'Technology', type: 'multiple', difficulty: 'medium',
    question: 'What does "CPU" stand for?',
    correct_answer: 'Central Processing Unit',
    answers: ['Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Core Processing Utility'] },
  { id: 'f-tc-4', category: 'Technology', type: 'multiple', difficulty: 'hard',
    question: 'In what year was the first iPhone released?',
    correct_answer: '2007',
    answers: ['2007', '2005', '2009', '2010'] },
  { id: 'f-tc-5', category: 'Technology', type: 'multiple', difficulty: 'easy',
    question: 'Which company makes the Pixel phone?',
    correct_answer: 'Google',
    answers: ['Google', 'Apple', 'Samsung', 'Sony'] },
  { id: 'f-tc-6', category: 'Technology', type: 'multiple', difficulty: 'medium',
    question: 'What programming language was created by Brendan Eich?',
    correct_answer: 'JavaScript',
    answers: ['JavaScript', 'Python', 'Java', 'Ruby'] },

  // ── History ───────────────────────────────────────────────────────────
  { id: 'f-hi-1', category: 'History', type: 'multiple', difficulty: 'easy',
    question: 'In what year did World War II end?',
    correct_answer: '1945',
    answers: ['1945', '1943', '1947', '1941'] },
  { id: 'f-hi-2', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'Who was the first President of the United States?',
    correct_answer: 'George Washington',
    answers: ['George Washington', 'Thomas Jefferson', 'John Adams', 'Abraham Lincoln'] },
  { id: 'f-hi-3', category: 'History', type: 'multiple', difficulty: 'hard',
    question: 'In what year did the Berlin Wall fall?',
    correct_answer: '1989',
    answers: ['1989', '1991', '1987', '1990'] },
  { id: 'f-hi-4', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'Which empire built Machu Picchu?',
    correct_answer: 'Inca',
    answers: ['Inca', 'Aztec', 'Maya', 'Olmec'] },
  { id: 'f-hi-5', category: 'History', type: 'multiple', difficulty: 'easy',
    question: 'What ancient wonder stood in Alexandria?',
    correct_answer: 'The Lighthouse',
    answers: ['The Lighthouse', 'The Colosseum', 'The Pyramids', 'The Parthenon'] },
  { id: 'f-hi-6', category: 'History', type: 'multiple', difficulty: 'hard',
    question: 'Who was the longest-reigning British monarch?',
    correct_answer: 'Elizabeth II',
    answers: ['Elizabeth II', 'Victoria', 'George III', 'Edward VII'] },

  // ── Sports ────────────────────────────────────────────────────────────
  { id: 'f-sp-1', category: 'Sports', type: 'boolean', difficulty: 'easy',
    question: 'The FIFA World Cup is held every 4 years.',
    correct_answer: 'True',
    answers: ['True', 'False'] },
  { id: 'f-sp-2', category: 'Sports', type: 'multiple', difficulty: 'medium',
    question: 'How many players are on a standard soccer team on the field?',
    correct_answer: '11',
    answers: ['11', '10', '12', '9'] },
  { id: 'f-sp-3', category: 'Sports', type: 'multiple', difficulty: 'easy',
    question: 'In what sport is "love" a score of zero?',
    correct_answer: 'Tennis',
    answers: ['Tennis', 'Cricket', 'Golf', 'Volleyball'] },
  { id: 'f-sp-4', category: 'Sports', type: 'multiple', difficulty: 'hard',
    question: 'Which country has won the most FIFA World Cups?',
    correct_answer: 'Brazil',
    answers: ['Brazil', 'Germany', 'Italy', 'Argentina'] },
  { id: 'f-sp-5', category: 'Sports', type: 'multiple', difficulty: 'medium',
    question: 'How many points is a touchdown worth in American football?',
    correct_answer: '6',
    answers: ['6', '7', '3', '5'] },
  { id: 'f-sp-6', category: 'Sports', type: 'multiple', difficulty: 'easy',
    question: 'In which sport is the Tour de France held?',
    correct_answer: 'Cycling',
    answers: ['Cycling', 'Running', 'Triathlon', 'Skiing'] },

  // ── Pop Culture ───────────────────────────────────────────────────────
  { id: 'f-pp-1', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'Who sang "Shape of You"?',
    correct_answer: 'Ed Sheeran',
    answers: ['Ed Sheeran', 'Justin Bieber', 'Charlie Puth', 'Sam Smith'] },
  { id: 'f-pp-2', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'Which film won Best Picture at the 2020 Oscars?',
    correct_answer: 'Parasite',
    answers: ['Parasite', '1917', 'Joker', 'Once Upon a Time in Hollywood'] },
  { id: 'f-pp-3', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'Who plays Tony Stark in the Marvel films?',
    correct_answer: 'Robert Downey Jr.',
    answers: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth'] },
  { id: 'f-pp-4', category: 'Pop Culture', type: 'multiple', difficulty: 'hard',
    question: 'What is the name of the wizarding school in Harry Potter?',
    correct_answer: 'Hogwarts',
    answers: ['Hogwarts', 'Beauxbatons', 'Durmstrang', 'Ilvermorny'] },
  { id: 'f-pp-5', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'Which TV show features Walter White?',
    correct_answer: 'Breaking Bad',
    answers: ['Breaking Bad', 'The Wire', 'Better Call Saul', 'Ozark'] },
  { id: 'f-pp-6', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'Which streaming service produced "Stranger Things"?',
    correct_answer: 'Netflix',
    answers: ['Netflix', 'Disney+', 'HBO Max', 'Prime Video'] },

  // ── Mixed / General Knowledge ─────────────────────────────────────────
  { id: 'f-gk-1', category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'What is the capital of France?',
    correct_answer: 'Paris',
    answers: ['Paris', 'London', 'Berlin', 'Madrid'] },
  { id: 'f-gk-2', category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'How many continents are there?',
    correct_answer: '7',
    answers: ['7', '6', '5', '8'] },
  { id: 'f-gk-3', category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'Which is the largest ocean on Earth?',
    correct_answer: 'Pacific',
    answers: ['Pacific', 'Atlantic', 'Indian', 'Arctic'] },
  { id: 'f-gk-4', category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'Mount Everest is in which mountain range?',
    correct_answer: 'Himalayas',
    answers: ['Himalayas', 'Andes', 'Alps', 'Rockies'] },

  // ── Science (additions) ────────────────────────────────────────────────
  { id: 'f-sc-9',  category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'What part of the eye controls how much light enters?',
    correct_answer: 'Iris',
    answers: ['Iris', 'Cornea', 'Retina', 'Lens'] },
  { id: 'f-sc-10', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'Which planet has the most moons (as of 2025)?',
    correct_answer: 'Saturn',
    answers: ['Saturn', 'Jupiter', 'Neptune', 'Uranus'] },
  { id: 'f-sc-11', category: 'Science', type: 'multiple', difficulty: 'hard',
    question: 'What is the powerhouse of the cell?',
    correct_answer: 'Mitochondria',
    answers: ['Mitochondria', 'Nucleus', 'Ribosome', 'Golgi'] },
  { id: 'f-sc-12', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'What gas do humans exhale?',
    correct_answer: 'Carbon dioxide',
    answers: ['Carbon dioxide', 'Oxygen', 'Hydrogen', 'Helium'] },
  { id: 'f-sc-13', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'What is the boiling point of water at sea level (°C)?',
    correct_answer: '100',
    answers: ['100', '90', '120', '212'] },
  { id: 'f-sc-14', category: 'Science', type: 'multiple', difficulty: 'hard',
    question: 'Which scientist proposed the theory of general relativity?',
    correct_answer: 'Einstein',
    answers: ['Einstein', 'Newton', 'Bohr', 'Hawking'] },
  { id: 'f-sc-15', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'What is the chemical symbol for sodium?',
    correct_answer: 'Na',
    answers: ['Na', 'So', 'Sd', 'S'] },
  { id: 'f-sc-16', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'How many planets are in our solar system?',
    correct_answer: '8',
    answers: ['8', '7', '9', '10'] },

  // ── History (additions) ────────────────────────────────────────────────
  { id: 'f-hi-11', category: 'History', type: 'multiple', difficulty: 'easy',
    question: 'Who was the first emperor of Rome?',
    correct_answer: 'Augustus',
    answers: ['Augustus', 'Julius Caesar', 'Nero', 'Hadrian'] },
  { id: 'f-hi-12', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'The Magna Carta was signed in which year?',
    correct_answer: '1215',
    answers: ['1215', '1066', '1415', '1305'] },
  { id: 'f-hi-7',  category: 'History', type: 'multiple', difficulty: 'hard',
    question: 'Who painted "The Last Supper"?',
    correct_answer: 'Leonardo da Vinci',
    answers: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello'] },
  { id: 'f-hi-8',  category: 'History', type: 'multiple', difficulty: 'easy',
    question: 'Which civilization built the pyramids of Giza?',
    correct_answer: 'Egyptian',
    answers: ['Egyptian', 'Roman', 'Greek', 'Mayan'] },
  { id: 'f-hi-9',  category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'The French Revolution began in what year?',
    correct_answer: '1789',
    answers: ['1789', '1799', '1776', '1812'] },
  { id: 'f-hi-10', category: 'History', type: 'multiple', difficulty: 'hard',
    question: 'Which empire was ruled by Genghis Khan?',
    correct_answer: 'Mongol',
    answers: ['Mongol', 'Ottoman', 'Persian', 'Roman'] },

  // ── Tech (additions) ───────────────────────────────────────────────────
  { id: 'f-te-4', category: 'Tech', type: 'multiple', difficulty: 'easy',
    question: 'What does "HTTP" stand for?',
    correct_answer: 'HyperText Transfer Protocol',
    answers: ['HyperText Transfer Protocol', 'High Tech Transfer Protocol', 'Hyper Transfer Text Protocol', 'Home Tool Transfer Protocol'] },
  { id: 'f-te-5', category: 'Tech', type: 'multiple', difficulty: 'medium',
    question: 'Who co-founded Apple alongside Steve Jobs?',
    correct_answer: 'Steve Wozniak',
    answers: ['Steve Wozniak', 'Bill Gates', 'Tim Cook', 'Jonathan Ive'] },
  { id: 'f-te-6', category: 'Tech', type: 'multiple', difficulty: 'hard',
    question: 'Which language compiles to "bytecode" that runs on the JVM?',
    correct_answer: 'Java',
    answers: ['Java', 'C++', 'Python', 'Rust'] },
  { id: 'f-te-7', category: 'Tech', type: 'multiple', difficulty: 'easy',
    question: 'What does "RAM" stand for?',
    correct_answer: 'Random Access Memory',
    answers: ['Random Access Memory', 'Read All Memory', 'Run And Manage', 'Rapid Active Module'] },
  { id: 'f-te-8', category: 'Tech', type: 'multiple', difficulty: 'medium',
    question: 'Which company created the Android operating system originally?',
    correct_answer: 'Android Inc.',
    answers: ['Android Inc.', 'Google', 'Samsung', 'Microsoft'] },
  { id: 'f-te-9', category: 'Tech', type: 'multiple', difficulty: 'hard',
    question: 'What does "API" stand for?',
    correct_answer: 'Application Programming Interface',
    answers: ['Application Programming Interface', 'Applied Programming Interface', 'Advanced Program Interface', 'App Process Interface'] },

  // ── Pop culture (additions) ────────────────────────────────────────────
  { id: 'f-po-4', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'Which artist released the album "1989"?',
    correct_answer: 'Taylor Swift',
    answers: ['Taylor Swift', 'Beyoncé', 'Adele', 'Rihanna'] },
  { id: 'f-po-5', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'In Harry Potter, what is the name of Harry\'s owl?',
    correct_answer: 'Hedwig',
    answers: ['Hedwig', 'Errol', 'Pigwidgeon', 'Crookshanks'] },
  { id: 'f-po-6', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'Which streaming service produced "Stranger Things"?',
    correct_answer: 'Netflix',
    answers: ['Netflix', 'Disney+', 'HBO Max', 'Prime Video'] },
  { id: 'f-po-7', category: 'Pop Culture', type: 'multiple', difficulty: 'hard',
    question: 'Who directed the 2019 film "Parasite"?',
    correct_answer: 'Bong Joon-ho',
    answers: ['Bong Joon-ho', 'Park Chan-wook', 'Hayao Miyazaki', 'Christopher Nolan'] },
  { id: 'f-po-8', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'In "The Office" (US), what paper company does the show center on?',
    correct_answer: 'Dunder Mifflin',
    answers: ['Dunder Mifflin', 'Vance Refrigeration', 'Schrute Farms', 'Sabre'] },
  { id: 'f-po-9', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'Which superhero is also known as "The Caped Crusader"?',
    correct_answer: 'Batman',
    answers: ['Batman', 'Superman', 'Spider-Man', 'Iron Man'] },

  // ── GK (additions) ─────────────────────────────────────────────────────
  { id: 'f-gk-5',  category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'How many sides does a hexagon have?',
    correct_answer: '6',
    answers: ['6', '5', '7', '8'] },
  { id: 'f-gk-6',  category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'What is the currency of Japan?',
    correct_answer: 'Yen',
    answers: ['Yen', 'Won', 'Yuan', 'Rupee'] },
  { id: 'f-gk-7',  category: 'General Knowledge', type: 'multiple', difficulty: 'hard',
    question: 'Which is the longest river in the world?',
    correct_answer: 'Nile',
    answers: ['Nile', 'Amazon', 'Yangtze', 'Mississippi'] },
  { id: 'f-gk-8',  category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'How many minutes are in a full day?',
    correct_answer: '1440',
    answers: ['1440', '720', '2400', '1200'] },
  { id: 'f-gk-9',  category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'What is the smallest country in the world by area?',
    correct_answer: 'Vatican City',
    answers: ['Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'] },
  { id: 'f-gk-10', category: 'General Knowledge', type: 'multiple', difficulty: 'hard',
    question: 'Which planet has a day longer than its year?',
    correct_answer: 'Venus',
    answers: ['Venus', 'Mercury', 'Mars', 'Jupiter'] },
  { id: 'f-gk-11', category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'How many colors are in a rainbow?',
    correct_answer: '7',
    answers: ['7', '6', '8', '5'] },
  { id: 'f-gk-12', category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'Which famous landmark is in Paris, France?',
    correct_answer: 'Eiffel Tower',
    answers: ['Eiffel Tower', 'Big Ben', 'Colosseum', 'Statue of Liberty'] },

  // ── Math (additions) ───────────────────────────────────────────────────
  { id: 'f-ma-1', category: 'Math', type: 'multiple', difficulty: 'easy',
    question: 'What is 12 × 12?',
    correct_answer: '144',
    answers: ['144', '124', '142', '154'] },
  { id: 'f-ma-2', category: 'Math', type: 'multiple', difficulty: 'medium',
    question: 'What is the square root of 169?',
    correct_answer: '13',
    answers: ['13', '12', '14', '15'] },
  { id: 'f-ma-3', category: 'Math', type: 'multiple', difficulty: 'hard',
    question: 'What is 15% of 200?',
    correct_answer: '30',
    answers: ['30', '20', '25', '35'] },
  { id: 'f-ma-4', category: 'Math', type: 'multiple', difficulty: 'easy',
    question: 'What is the value of π (rounded to two decimals)?',
    correct_answer: '3.14',
    answers: ['3.14', '3.41', '2.14', '3.04'] },
  { id: 'f-ma-5', category: 'Math', type: 'multiple', difficulty: 'medium',
    question: 'How many degrees are in a right angle?',
    correct_answer: '90',
    answers: ['90', '60', '120', '180'] },

  // ── Sports (additions) ─────────────────────────────────────────────────
  { id: 'f-sp-7', category: 'Sports', type: 'multiple', difficulty: 'easy',
    question: 'How many players are on a basketball team on the court?',
    correct_answer: '5',
    answers: ['5', '6', '7', '4'] },
  { id: 'f-sp-8', category: 'Sports', type: 'multiple', difficulty: 'medium',
    question: 'In which sport would you perform a "slam dunk"?',
    correct_answer: 'Basketball',
    answers: ['Basketball', 'Volleyball', 'Tennis', 'Football'] },
  { id: 'f-sp-9', category: 'Sports', type: 'multiple', difficulty: 'hard',
    question: 'Where were the 2024 Summer Olympics held?',
    correct_answer: 'Paris',
    answers: ['Paris', 'Tokyo', 'Los Angeles', 'London'] },
  { id: 'f-sp-10', category: 'Sports', type: 'multiple', difficulty: 'easy',
    question: 'How many rings are on the Olympic flag?',
    correct_answer: '5',
    answers: ['5', '4', '6', '7'] },

  // ── Science (new batch) ───────────────────────────────────────────────
  { id: 'f-sc-17', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'What gas makes up most of Earth\'s atmosphere?',
    correct_answer: 'Nitrogen',
    answers: ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Argon'] },
  { id: 'f-sc-18', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'What organ pumps blood through the human body?',
    correct_answer: 'Heart',
    answers: ['Heart', 'Lung', 'Liver', 'Kidney'] },
  { id: 'f-sc-19', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'Which planet is closest to the Sun?',
    correct_answer: 'Mercury',
    answers: ['Mercury', 'Venus', 'Earth', 'Mars'] },
  { id: 'f-sc-20', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'What is the hardest natural substance on Earth?',
    correct_answer: 'Diamond',
    answers: ['Diamond', 'Quartz', 'Titanium', 'Corundum'] },
  { id: 'f-sc-21', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'How many chambers does the human heart have?',
    correct_answer: '4',
    answers: ['4', '2', '3', '6'] },
  { id: 'f-sc-22', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'What type of animal is a dolphin?',
    correct_answer: 'Mammal',
    answers: ['Mammal', 'Fish', 'Reptile', 'Amphibian'] },
  { id: 'f-sc-23', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'What is the chemical symbol for iron?',
    correct_answer: 'Fe',
    answers: ['Fe', 'Ir', 'In', 'Fo'] },
  { id: 'f-sc-24', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'Which force keeps the Moon in orbit around Earth?',
    correct_answer: 'Gravity',
    answers: ['Gravity', 'Magnetism', 'Electrostatic force', 'Nuclear force'] },
  { id: 'f-sc-25', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'What unit measures electrical resistance?',
    correct_answer: 'Ohm',
    answers: ['Ohm', 'Volt', 'Ampere', 'Watt'] },
  { id: 'f-sc-26', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'DNA stands for what?',
    correct_answer: 'Deoxyribonucleic acid',
    answers: ['Deoxyribonucleic acid', 'Dinitrogen acid', 'Deoxyribose nitrogen acid', 'Dinucleotide acid'] },
  { id: 'f-sc-27', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'What is the atomic number of carbon?',
    correct_answer: '6',
    answers: ['6', '12', '8', '4'] },
  { id: 'f-sc-28', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'Which layer of the atmosphere contains the ozone layer?',
    correct_answer: 'Stratosphere',
    answers: ['Stratosphere', 'Troposphere', 'Mesosphere', 'Thermosphere'] },
  { id: 'f-sc-29', category: 'Science', type: 'multiple', difficulty: 'hard',
    question: 'What is the half-life of Carbon-14?',
    correct_answer: '5,730 years',
    answers: ['5,730 years', '1,600 years', '10,000 years', '3,200 years'] },
  { id: 'f-sc-30', category: 'Science', type: 'multiple', difficulty: 'hard',
    question: 'What is the name of the process by which plants make food?',
    correct_answer: 'Photosynthesis',
    answers: ['Photosynthesis', 'Respiration', 'Osmosis', 'Transpiration'] },
  { id: 'f-sc-31', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'Which gas is produced when an acid reacts with a metal?',
    correct_answer: 'Hydrogen',
    answers: ['Hydrogen', 'Oxygen', 'Carbon dioxide', 'Nitrogen'] },
  { id: 'f-sc-32', category: 'Science', type: 'multiple', difficulty: 'hard',
    question: 'What is the SI unit of electric current?',
    correct_answer: 'Ampere',
    answers: ['Ampere', 'Volt', 'Coulomb', 'Watt'] },
  { id: 'f-sc-33', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'What is the largest organ in the human body?',
    correct_answer: 'Skin',
    answers: ['Skin', 'Liver', 'Brain', 'Intestine'] },
  { id: 'f-sc-34', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'Newton\'s first law is also called the law of what?',
    correct_answer: 'Inertia',
    answers: ['Inertia', 'Gravity', 'Motion', 'Acceleration'] },
  { id: 'f-sc-35', category: 'Science', type: 'multiple', difficulty: 'hard',
    question: 'What subatomic particle has a negative charge?',
    correct_answer: 'Electron',
    answers: ['Electron', 'Proton', 'Neutron', 'Positron'] },
  { id: 'f-sc-36', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'Which planet is the largest in our solar system?',
    correct_answer: 'Jupiter',
    answers: ['Jupiter', 'Saturn', 'Neptune', 'Uranus'] },
  { id: 'f-sc-37', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'What is the chemical formula for water?',
    correct_answer: 'H₂O',
    answers: ['H₂O', 'HO₂', 'H₂O₂', 'CO₂'] },
  { id: 'f-sc-38', category: 'Science', type: 'multiple', difficulty: 'hard',
    question: 'Which element is liquid at room temperature besides mercury?',
    correct_answer: 'Bromine',
    answers: ['Bromine', 'Gallium', 'Cesium', 'Fluorine'] },
  { id: 'f-sc-39', category: 'Science', type: 'multiple', difficulty: 'easy',
    question: 'Sound travels fastest through which medium?',
    correct_answer: 'Solid',
    answers: ['Solid', 'Liquid', 'Gas', 'Vacuum'] },
  { id: 'f-sc-40', category: 'Science', type: 'multiple', difficulty: 'medium',
    question: 'What is the pH of pure water?',
    correct_answer: '7',
    answers: ['7', '0', '14', '5'] },
  { id: 'f-sc-41', category: 'Science', type: 'multiple', difficulty: 'hard',
    question: 'What is the most abundant element in the universe?',
    correct_answer: 'Hydrogen',
    answers: ['Hydrogen', 'Helium', 'Oxygen', 'Carbon'] },

  // ── History (new batch) ───────────────────────────────────────────────
  { id: 'f-hi-13', category: 'History', type: 'multiple', difficulty: 'easy',
    question: 'In which country was the gunpowder first invented?',
    correct_answer: 'China',
    answers: ['China', 'India', 'Persia', 'Egypt'] },
  { id: 'f-hi-14', category: 'History', type: 'multiple', difficulty: 'easy',
    question: 'Which ancient city was destroyed by a volcanic eruption in 79 AD?',
    correct_answer: 'Pompeii',
    answers: ['Pompeii', 'Carthage', 'Rome', 'Athens'] },
  { id: 'f-hi-15', category: 'History', type: 'multiple', difficulty: 'easy',
    question: 'The ancient Olympics were held in which country?',
    correct_answer: 'Greece',
    answers: ['Greece', 'Italy', 'Egypt', 'Turkey'] },
  { id: 'f-hi-16', category: 'History', type: 'multiple', difficulty: 'easy',
    question: 'What structure did Emperor Qin Shi Huang famously build?',
    correct_answer: 'The Great Wall of China',
    answers: ['The Great Wall of China', 'The Colosseum', 'The Taj Mahal', 'The Acropolis'] },
  { id: 'f-hi-17', category: 'History', type: 'multiple', difficulty: 'easy',
    question: 'Which country gifted the Statue of Liberty to the United States?',
    correct_answer: 'France',
    answers: ['France', 'United Kingdom', 'Spain', 'Germany'] },
  { id: 'f-hi-18', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'In what year did Christopher Columbus reach the Americas?',
    correct_answer: '1492',
    answers: ['1492', '1498', '1510', '1488'] },
  { id: 'f-hi-19', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'What was the name of the ancient trade route connecting East and West?',
    correct_answer: 'Silk Road',
    answers: ['Silk Road', 'Spice Trail', 'Golden Path', 'Salt Route'] },
  { id: 'f-hi-20', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'Who was the Egyptian queen famous for her relationship with Julius Caesar?',
    correct_answer: 'Cleopatra',
    answers: ['Cleopatra', 'Nefertiti', 'Hatshepsut', 'Isis'] },
  { id: 'f-hi-21', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'World War I began in what year?',
    correct_answer: '1914',
    answers: ['1914', '1918', '1912', '1916'] },
  { id: 'f-hi-22', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'The Renaissance began in which country?',
    correct_answer: 'Italy',
    answers: ['Italy', 'France', 'Germany', 'Spain'] },
  { id: 'f-hi-23', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'The Titanic sank in what year?',
    correct_answer: '1912',
    answers: ['1912', '1914', '1910', '1918'] },
  { id: 'f-hi-24', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'Neil Armstrong landed on the Moon during which NASA mission?',
    correct_answer: 'Apollo 11',
    answers: ['Apollo 11', 'Apollo 13', 'Gemini 7', 'Apollo 8'] },
  { id: 'f-hi-25', category: 'History', type: 'multiple', difficulty: 'hard',
    question: 'The Battle of Hastings took place in what year?',
    correct_answer: '1066',
    answers: ['1066', '1215', '1189', '1099'] },
  { id: 'f-hi-26', category: 'History', type: 'multiple', difficulty: 'hard',
    question: 'Who was the leader of the Soviet Union during World War II?',
    correct_answer: 'Joseph Stalin',
    answers: ['Joseph Stalin', 'Lenin', 'Khrushchev', 'Brezhnev'] },
  { id: 'f-hi-27', category: 'History', type: 'multiple', difficulty: 'hard',
    question: 'The Treaty of Versailles ended which war?',
    correct_answer: 'World War I',
    answers: ['World War I', 'World War II', 'The Crimean War', 'The Franco-Prussian War'] },
  { id: 'f-hi-28', category: 'History', type: 'multiple', difficulty: 'hard',
    question: 'Which empire was the largest in history by land area?',
    correct_answer: 'British Empire',
    answers: ['British Empire', 'Mongol Empire', 'Russian Empire', 'Roman Empire'] },
  { id: 'f-hi-29', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'The printing press was invented by whom?',
    correct_answer: 'Johannes Gutenberg',
    answers: ['Johannes Gutenberg', 'Leonardo da Vinci', 'Galileo Galilei', 'Isaac Newton'] },
  { id: 'f-hi-30', category: 'History', type: 'multiple', difficulty: 'easy',
    question: 'In what country was the first modern Olympic Games held in 1896?',
    correct_answer: 'Greece',
    answers: ['Greece', 'France', 'England', 'USA'] },
  { id: 'f-hi-31', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'The Boston Tea Party took place in which year?',
    correct_answer: '1773',
    answers: ['1773', '1776', '1783', '1765'] },
  { id: 'f-hi-32', category: 'History', type: 'multiple', difficulty: 'hard',
    question: 'Who was the last pharaoh of ancient Egypt?',
    correct_answer: 'Cleopatra VII',
    answers: ['Cleopatra VII', 'Ramesses II', 'Tutankhamun', 'Nefertiti'] },
  { id: 'f-hi-33', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'The Aztec Empire was conquered by which European explorer?',
    correct_answer: 'Hernán Cortés',
    answers: ['Hernán Cortés', 'Francisco Pizarro', 'Christopher Columbus', 'Vasco da Gama'] },
  { id: 'f-hi-34', category: 'History', type: 'multiple', difficulty: 'easy',
    question: 'In which year did humans first walk on the Moon?',
    correct_answer: '1969',
    answers: ['1969', '1965', '1972', '1975'] },
  { id: 'f-hi-35', category: 'History', type: 'multiple', difficulty: 'hard',
    question: 'The Peloponnesian War was fought between which two city-states?',
    correct_answer: 'Athens and Sparta',
    answers: ['Athens and Sparta', 'Rome and Carthage', 'Thebes and Corinth', 'Athens and Corinth'] },
  { id: 'f-hi-36', category: 'History', type: 'multiple', difficulty: 'medium',
    question: 'Which famous scientist was born on the same day Darwin died — April 19, 1882?',
    correct_answer: 'None — this is a myth',
    answers: ['None — this is a myth', 'Niels Bohr', 'Max Planck', 'Albert Einstein'] },

  // ── Tech (new batch) ──────────────────────────────────────────────────
  { id: 'f-te-10', category: 'Tech', type: 'multiple', difficulty: 'easy',
    question: 'What does "USB" stand for?',
    correct_answer: 'Universal Serial Bus',
    answers: ['Universal Serial Bus', 'Unified System Bus', 'Universal System Buffer', 'Unified Serial Bus'] },
  { id: 'f-te-11', category: 'Tech', type: 'multiple', difficulty: 'easy',
    question: 'What does "Wi-Fi" stand for?',
    correct_answer: 'Wireless Fidelity',
    answers: ['Wireless Fidelity', 'Wired Fidelity', 'Wide Frequency', 'Wireless Frequency'] },
  { id: 'f-te-12', category: 'Tech', type: 'multiple', difficulty: 'easy',
    question: 'Which company makes the macOS operating system?',
    correct_answer: 'Apple',
    answers: ['Apple', 'Microsoft', 'Google', 'IBM'] },
  { id: 'f-te-13', category: 'Tech', type: 'multiple', difficulty: 'easy',
    question: 'What is the most widely used search engine in the world?',
    correct_answer: 'Google',
    answers: ['Google', 'Bing', 'Yahoo', 'DuckDuckGo'] },
  { id: 'f-te-14', category: 'Tech', type: 'multiple', difficulty: 'medium',
    question: 'What year was the World Wide Web publicly available?',
    correct_answer: '1991',
    answers: ['1991', '1989', '1995', '1983'] },
  { id: 'f-te-15', category: 'Tech', type: 'multiple', difficulty: 'medium',
    question: 'Which programming language is primarily used for iOS app development?',
    correct_answer: 'Swift',
    answers: ['Swift', 'Kotlin', 'Java', 'Objective-C'] },
  { id: 'f-te-16', category: 'Tech', type: 'multiple', difficulty: 'medium',
    question: 'What does "SSD" stand for in computing?',
    correct_answer: 'Solid State Drive',
    answers: ['Solid State Drive', 'Super Speed Disk', 'Static Storage Device', 'Solid Storage Data'] },
  { id: 'f-te-17', category: 'Tech', type: 'multiple', difficulty: 'medium',
    question: 'Which company developed the Python programming language?',
    correct_answer: 'Guido van Rossum',
    answers: ['Guido van Rossum', 'Linus Torvalds', 'Dennis Ritchie', 'James Gosling'] },
  { id: 'f-te-18', category: 'Tech', type: 'multiple', difficulty: 'medium',
    question: 'What does "GPU" stand for?',
    correct_answer: 'Graphics Processing Unit',
    answers: ['Graphics Processing Unit', 'General Processing Unit', 'Graphic Program Utility', 'Global Processing Unit'] },
  { id: 'f-te-19', category: 'Tech', type: 'multiple', difficulty: 'hard',
    question: 'Which data structure operates on a LIFO (Last In, First Out) principle?',
    correct_answer: 'Stack',
    answers: ['Stack', 'Queue', 'Linked List', 'Tree'] },
  { id: 'f-te-20', category: 'Tech', type: 'multiple', difficulty: 'hard',
    question: 'What is the binary representation of the decimal number 10?',
    correct_answer: '1010',
    answers: ['1010', '1001', '1100', '0110'] },
  { id: 'f-te-21', category: 'Tech', type: 'multiple', difficulty: 'hard',
    question: 'Which sorting algorithm has an average time complexity of O(n log n)?',
    correct_answer: 'Merge Sort',
    answers: ['Merge Sort', 'Bubble Sort', 'Selection Sort', 'Insertion Sort'] },
  { id: 'f-te-22', category: 'Tech', type: 'multiple', difficulty: 'medium',
    question: 'What language is primarily used for styling web pages?',
    correct_answer: 'CSS',
    answers: ['CSS', 'HTML', 'JavaScript', 'SQL'] },
  { id: 'f-te-23', category: 'Tech', type: 'multiple', difficulty: 'easy',
    question: 'What does "OS" stand for in computing?',
    correct_answer: 'Operating System',
    answers: ['Operating System', 'Open Source', 'Output System', 'Optical Storage'] },
  { id: 'f-te-24', category: 'Tech', type: 'multiple', difficulty: 'medium',
    question: 'What does "SQL" stand for?',
    correct_answer: 'Structured Query Language',
    answers: ['Structured Query Language', 'Simple Query Language', 'Standard Query Loop', 'Sequential Query Language'] },
  { id: 'f-te-25', category: 'Tech', type: 'multiple', difficulty: 'hard',
    question: 'Who created the Linux kernel?',
    correct_answer: 'Linus Torvalds',
    answers: ['Linus Torvalds', 'Richard Stallman', 'Ken Thompson', 'Dennis Ritchie'] },
  { id: 'f-te-26', category: 'Tech', type: 'multiple', difficulty: 'medium',
    question: 'Which company owns YouTube?',
    correct_answer: 'Google',
    answers: ['Google', 'Meta', 'Amazon', 'Microsoft'] },
  { id: 'f-te-27', category: 'Tech', type: 'multiple', difficulty: 'easy',
    question: 'What does "PDF" stand for?',
    correct_answer: 'Portable Document Format',
    answers: ['Portable Document Format', 'Printed Document File', 'Personal Document Format', 'Print Data File'] },
  { id: 'f-te-28', category: 'Tech', type: 'multiple', difficulty: 'medium',
    question: 'Git was created by whom?',
    correct_answer: 'Linus Torvalds',
    answers: ['Linus Torvalds', 'Bill Gates', 'Guido van Rossum', 'James Gosling'] },
  { id: 'f-te-29', category: 'Tech', type: 'multiple', difficulty: 'hard',
    question: 'What is the IPv4 loopback address?',
    correct_answer: '127.0.0.1',
    answers: ['127.0.0.1', '192.168.0.1', '0.0.0.0', '255.255.255.0'] },

  // ── Pop Culture (new batch) ────────────────────────────────────────────
  { id: 'f-po-10', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'Which band performed "Bohemian Rhapsody"?',
    correct_answer: 'Queen',
    answers: ['Queen', 'The Beatles', 'Led Zeppelin', 'Pink Floyd'] },
  { id: 'f-po-11', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'Who is the fictional wizard created by J.K. Rowling?',
    correct_answer: 'Harry Potter',
    answers: ['Harry Potter', 'Gandalf', 'Merlin', 'Dumbledore'] },
  { id: 'f-po-12', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'Which Disney movie features the song "Let It Go"?',
    correct_answer: 'Frozen',
    answers: ['Frozen', 'Tangled', 'Brave', 'Moana'] },
  { id: 'f-po-13', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'Who voiced Buzz Lightyear in the original Toy Story?',
    correct_answer: 'Tim Allen',
    answers: ['Tim Allen', 'Tom Hanks', 'Jim Carrey', 'Robin Williams'] },
  { id: 'f-po-14', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'In "Game of Thrones", what is the motto of House Stark?',
    correct_answer: 'Winter is Coming',
    answers: ['Winter is Coming', 'Fire and Blood', 'Hear Me Roar', 'Growing Strong'] },
  { id: 'f-po-15', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'Which singer is known as the "Queen of Pop"?',
    correct_answer: 'Madonna',
    answers: ['Madonna', 'Beyoncé', 'Lady Gaga', 'Whitney Houston'] },
  { id: 'f-po-16', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'The movie "The Lion King" is set in which continent?',
    correct_answer: 'Africa',
    answers: ['Africa', 'Asia', 'South America', 'Australia'] },
  { id: 'f-po-17', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'Which fast food chain\'s mascot is a clown?',
    correct_answer: 'McDonald\'s',
    answers: ['McDonald\'s', 'Burger King', 'Wendy\'s', 'Jack in the Box'] },
  { id: 'f-po-18', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'In "Friends", what is the name of Ross\'s pet monkey?',
    correct_answer: 'Marcel',
    answers: ['Marcel', 'Bubbles', 'Spike', 'Coco'] },
  { id: 'f-po-19', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'Which animated series features the characters Homer, Marge, Bart and Lisa?',
    correct_answer: 'The Simpsons',
    answers: ['The Simpsons', 'Family Guy', 'Futurama', 'Bob\'s Burgers'] },
  { id: 'f-po-20', category: 'Pop Culture', type: 'multiple', difficulty: 'hard',
    question: 'Which film won the first-ever Academy Award for Best Picture?',
    correct_answer: 'Wings',
    answers: ['Wings', 'The Artist', 'Sunrise', 'Seventh Heaven'] },
  { id: 'f-po-21', category: 'Pop Culture', type: 'multiple', difficulty: 'hard',
    question: 'What is the name of the fictional country in "Black Panther"?',
    correct_answer: 'Wakanda',
    answers: ['Wakanda', 'Zamunda', 'Genovia', 'Sokovia'] },
  { id: 'f-po-22', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'Which singer released the album "Thriller"?',
    correct_answer: 'Michael Jackson',
    answers: ['Michael Jackson', 'Prince', 'Elvis Presley', 'David Bowie'] },
  { id: 'f-po-23', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'Which actor plays Sherlock Holmes in the BBC series "Sherlock"?',
    correct_answer: 'Benedict Cumberbatch',
    answers: ['Benedict Cumberbatch', 'Tom Hiddleston', 'Colin Firth', 'Daniel Craig'] },
  { id: 'f-po-24', category: 'Pop Culture', type: 'multiple', difficulty: 'hard',
    question: 'What is the highest-grossing film of all time (not adjusted for inflation)?',
    correct_answer: 'Avatar',
    answers: ['Avatar', 'Avengers: Endgame', 'Titanic', 'The Lion King (2019)'] },
  { id: 'f-po-25', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'In the "Star Wars" universe, what color is Yoda?',
    correct_answer: 'Green',
    answers: ['Green', 'Blue', 'Red', 'Purple'] },
  { id: 'f-po-26', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'Which UK band released the album "Abbey Road"?',
    correct_answer: 'The Beatles',
    answers: ['The Beatles', 'The Rolling Stones', 'The Who', 'Pink Floyd'] },
  { id: 'f-po-27', category: 'Pop Culture', type: 'multiple', difficulty: 'easy',
    question: 'What is the name of the toy cowboy in "Toy Story"?',
    correct_answer: 'Woody',
    answers: ['Woody', 'Buzz', 'Rex', 'Hamm'] },
  { id: 'f-po-28', category: 'Pop Culture', type: 'multiple', difficulty: 'hard',
    question: 'Which TV show is set in the fictional town of Hawkins, Indiana?',
    correct_answer: 'Stranger Things',
    answers: ['Stranger Things', 'Dark', 'Twin Peaks', 'The OA'] },
  { id: 'f-po-29', category: 'Pop Culture', type: 'multiple', difficulty: 'medium',
    question: 'Which Marvel hero is known as "The Merc with a Mouth"?',
    correct_answer: 'Deadpool',
    answers: ['Deadpool', 'Spider-Man', 'Wolverine', 'Ant-Man'] },

  // ── General Knowledge (new batch) ─────────────────────────────────────
  { id: 'f-gk-13', category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'How many legs does a spider have?',
    correct_answer: '8',
    answers: ['8', '6', '10', '4'] },
  { id: 'f-gk-14', category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'What is the color of the sky on a clear day?',
    correct_answer: 'Blue',
    answers: ['Blue', 'White', 'Green', 'Yellow'] },
  { id: 'f-gk-15', category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'How many months have exactly 30 days?',
    correct_answer: '4',
    answers: ['4', '6', '3', '5'] },
  { id: 'f-gk-16', category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'Which animal is known as the "Ship of the Desert"?',
    correct_answer: 'Camel',
    answers: ['Camel', 'Horse', 'Donkey', 'Elephant'] },
  { id: 'f-gk-17', category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'Which vitamin does sunlight help the body produce?',
    correct_answer: 'Vitamin D',
    answers: ['Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B12'] },
  { id: 'f-gk-18', category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'What is the most spoken language in the world by native speakers?',
    correct_answer: 'Mandarin Chinese',
    answers: ['Mandarin Chinese', 'English', 'Spanish', 'Hindi'] },
  { id: 'f-gk-19', category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'What number does the Roman numeral "L" represent?',
    correct_answer: '50',
    answers: ['50', '100', '40', '60'] },
  { id: 'f-gk-20', category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'A group of lions is called a what?',
    correct_answer: 'Pride',
    answers: ['Pride', 'Pack', 'Herd', 'Flock'] },
  { id: 'f-gk-21', category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'How many strings does a standard guitar have?',
    correct_answer: '6',
    answers: ['6', '4', '8', '12'] },
  { id: 'f-gk-22', category: 'General Knowledge', type: 'multiple', difficulty: 'hard',
    question: 'What is the only country that lies in all four hemispheres?',
    correct_answer: 'Kiribati',
    answers: ['Kiribati', 'Ecuador', 'Brazil', 'Indonesia'] },
  { id: 'f-gk-23', category: 'General Knowledge', type: 'multiple', difficulty: 'hard',
    question: 'How many teeth does an adult human normally have?',
    correct_answer: '32',
    answers: ['32', '28', '30', '36'] },
  { id: 'f-gk-24', category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'Which planet is called the "Blue Planet"?',
    correct_answer: 'Earth',
    answers: ['Earth', 'Neptune', 'Uranus', 'Saturn'] },
  { id: 'f-gk-25', category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'What is the loudest animal in the world?',
    correct_answer: 'Sperm Whale',
    answers: ['Sperm Whale', 'Blue Whale', 'Howler Monkey', 'African Elephant'] },
  { id: 'f-gk-26', category: 'General Knowledge', type: 'multiple', difficulty: 'hard',
    question: 'Which organ in the human body produces insulin?',
    correct_answer: 'Pancreas',
    answers: ['Pancreas', 'Liver', 'Kidney', 'Spleen'] },
  { id: 'f-gk-27', category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'How many days are in a leap year?',
    correct_answer: '366',
    answers: ['366', '365', '364', '367'] },
  { id: 'f-gk-28', category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'What is the national animal of Canada?',
    correct_answer: 'Beaver',
    answers: ['Beaver', 'Moose', 'Bear', 'Bald Eagle'] },
  { id: 'f-gk-29', category: 'General Knowledge', type: 'multiple', difficulty: 'hard',
    question: 'What is the chemical symbol for gold?',
    correct_answer: 'Au',
    answers: ['Au', 'Ag', 'Go', 'Gd'] },
  { id: 'f-gk-30', category: 'General Knowledge', type: 'multiple', difficulty: 'easy',
    question: 'Which is the fastest land animal?',
    correct_answer: 'Cheetah',
    answers: ['Cheetah', 'Lion', 'Horse', 'Greyhound'] },
  { id: 'f-gk-31', category: 'General Knowledge', type: 'multiple', difficulty: 'medium',
    question: 'What is the longest bone in the human body?',
    correct_answer: 'Femur',
    answers: ['Femur', 'Tibia', 'Humerus', 'Fibula'] },
  { id: 'f-gk-32', category: 'General Knowledge', type: 'multiple', difficulty: 'hard',
    question: 'How many zeros are in one trillion?',
    correct_answer: '12',
    answers: ['12', '9', '15', '6'] },

  // ── Math (new batch) ──────────────────────────────────────────────────
  { id: 'f-ma-6', category: 'Math', type: 'multiple', difficulty: 'easy',
    question: 'What is 8 × 7?',
    correct_answer: '56',
    answers: ['56', '54', '48', '63'] },
  { id: 'f-ma-7', category: 'Math', type: 'multiple', difficulty: 'easy',
    question: 'What is the next prime number after 7?',
    correct_answer: '11',
    answers: ['11', '9', '10', '13'] },
  { id: 'f-ma-8', category: 'Math', type: 'multiple', difficulty: 'easy',
    question: 'How many degrees are in a full circle?',
    correct_answer: '360',
    answers: ['360', '180', '270', '90'] },
  { id: 'f-ma-9', category: 'Math', type: 'multiple', difficulty: 'easy',
    question: 'What is 100 ÷ 4?',
    correct_answer: '25',
    answers: ['25', '20', '30', '40'] },
  { id: 'f-ma-10', category: 'Math', type: 'multiple', difficulty: 'medium',
    question: 'What is the area of a circle with radius 5 (use π ≈ 3.14)?',
    correct_answer: '78.5',
    answers: ['78.5', '31.4', '25', '62.8'] },
  { id: 'f-ma-11', category: 'Math', type: 'multiple', difficulty: 'medium',
    question: 'What is the sum of interior angles of a triangle?',
    correct_answer: '180°',
    answers: ['180°', '360°', '90°', '270°'] },
  { id: 'f-ma-12', category: 'Math', type: 'multiple', difficulty: 'medium',
    question: 'What is 2 to the power of 10?',
    correct_answer: '1024',
    answers: ['1024', '512', '2048', '1000'] },
  { id: 'f-ma-13', category: 'Math', type: 'multiple', difficulty: 'medium',
    question: 'What is the square root of 256?',
    correct_answer: '16',
    answers: ['16', '14', '18', '12'] },
  { id: 'f-ma-14', category: 'Math', type: 'multiple', difficulty: 'medium',
    question: 'If a triangle has sides 3, 4, and 5, what type of triangle is it?',
    correct_answer: 'Right triangle',
    answers: ['Right triangle', 'Equilateral triangle', 'Obtuse triangle', 'Isosceles triangle'] },
  { id: 'f-ma-15', category: 'Math', type: 'multiple', difficulty: 'hard',
    question: 'What is the value of 0! (zero factorial)?',
    correct_answer: '1',
    answers: ['1', '0', 'Undefined', 'Infinity'] },
  { id: 'f-ma-16', category: 'Math', type: 'multiple', difficulty: 'hard',
    question: 'What is 7! (7 factorial)?',
    correct_answer: '5040',
    answers: ['5040', '720', '40320', '2520'] },
  { id: 'f-ma-17', category: 'Math', type: 'multiple', difficulty: 'hard',
    question: 'What is the sum of the first 10 natural numbers?',
    correct_answer: '55',
    answers: ['55', '45', '50', '60'] },
  { id: 'f-ma-18', category: 'Math', type: 'multiple', difficulty: 'easy',
    question: 'How many sides does an octagon have?',
    correct_answer: '8',
    answers: ['8', '6', '10', '7'] },
  { id: 'f-ma-19', category: 'Math', type: 'multiple', difficulty: 'medium',
    question: 'What is 25% of 400?',
    correct_answer: '100',
    answers: ['100', '80', '120', '50'] },
  { id: 'f-ma-20', category: 'Math', type: 'multiple', difficulty: 'hard',
    question: 'In a standard normal distribution, what percentage of data falls within one standard deviation of the mean?',
    correct_answer: '68%',
    answers: ['68%', '95%', '50%', '99.7%'] },

  // ── Sports (new batch) ────────────────────────────────────────────────
  { id: 'f-sp-11', category: 'Sports', type: 'multiple', difficulty: 'easy',
    question: 'What sport is played at Wimbledon?',
    correct_answer: 'Tennis',
    answers: ['Tennis', 'Cricket', 'Badminton', 'Squash'] },
  { id: 'f-sp-12', category: 'Sports', type: 'multiple', difficulty: 'easy',
    question: 'In baseball, how many strikes does it take to strike out a batter?',
    correct_answer: '3',
    answers: ['3', '2', '4', '5'] },
  { id: 'f-sp-13', category: 'Sports', type: 'multiple', difficulty: 'medium',
    question: 'Who holds the record for the most Grand Slam tennis titles among men (as of 2024)?',
    correct_answer: 'Novak Djokovic',
    answers: ['Novak Djokovic', 'Rafael Nadal', 'Roger Federer', 'Pete Sampras'] },
  { id: 'f-sp-14', category: 'Sports', type: 'multiple', difficulty: 'medium',
    question: 'A standard marathon is how many miles?',
    correct_answer: '26.2',
    answers: ['26.2', '24.6', '30', '13.1'] },
  { id: 'f-sp-15', category: 'Sports', type: 'multiple', difficulty: 'hard',
    question: 'In which year was the first Super Bowl played?',
    correct_answer: '1967',
    answers: ['1967', '1969', '1965', '1971'] },
  { id: 'f-sp-16', category: 'Sports', type: 'multiple', difficulty: 'easy',
    question: 'Which country invented the sport of basketball?',
    correct_answer: 'USA',
    answers: ['USA', 'Canada', 'United Kingdom', 'Spain'] },
  { id: 'f-sp-17', category: 'Sports', type: 'multiple', difficulty: 'medium',
    question: 'How many players are on each side in a volleyball match?',
    correct_answer: '6',
    answers: ['6', '5', '7', '9'] },
  { id: 'f-sp-18', category: 'Sports', type: 'multiple', difficulty: 'hard',
    question: 'What is the maximum score in a single game of bowling?',
    correct_answer: '300',
    answers: ['300', '250', '360', '280'] },
  { id: 'f-sp-19', category: 'Sports', type: 'multiple', difficulty: 'easy',
    question: 'How many holes are played in a standard round of golf?',
    correct_answer: '18',
    answers: ['18', '9', '12', '36'] },
  { id: 'f-sp-20', category: 'Sports', type: 'multiple', difficulty: 'medium',
    question: 'Which country has won the most Cricket World Cups?',
    correct_answer: 'Australia',
    answers: ['Australia', 'India', 'West Indies', 'England'] },

  // ── Geography (new category) ──────────────────────────────────────────
  { id: 'f-ge-1', category: 'Geography', type: 'multiple', difficulty: 'easy',
    question: 'What is the capital of Australia?',
    correct_answer: 'Canberra',
    answers: ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'] },
  { id: 'f-ge-2', category: 'Geography', type: 'multiple', difficulty: 'easy',
    question: 'Which river runs through Egypt?',
    correct_answer: 'Nile',
    answers: ['Nile', 'Amazon', 'Congo', 'Niger'] },
  { id: 'f-ge-3', category: 'Geography', type: 'multiple', difficulty: 'easy',
    question: 'What is the largest country in the world by area?',
    correct_answer: 'Russia',
    answers: ['Russia', 'Canada', 'China', 'USA'] },
  { id: 'f-ge-4', category: 'Geography', type: 'multiple', difficulty: 'easy',
    question: 'On which continent is the Sahara Desert located?',
    correct_answer: 'Africa',
    answers: ['Africa', 'Asia', 'South America', 'Australia'] },
  { id: 'f-ge-5', category: 'Geography', type: 'multiple', difficulty: 'easy',
    question: 'What is the capital of Japan?',
    correct_answer: 'Tokyo',
    answers: ['Tokyo', 'Osaka', 'Kyoto', 'Hiroshima'] },
  { id: 'f-ge-6', category: 'Geography', type: 'multiple', difficulty: 'medium',
    question: 'Which country has the most natural lakes?',
    correct_answer: 'Canada',
    answers: ['Canada', 'Russia', 'USA', 'Finland'] },
  { id: 'f-ge-7', category: 'Geography', type: 'multiple', difficulty: 'medium',
    question: 'What is the name of the longest mountain range in the world?',
    correct_answer: 'Andes',
    answers: ['Andes', 'Himalayas', 'Rocky Mountains', 'Alps'] },
  { id: 'f-ge-8', category: 'Geography', type: 'multiple', difficulty: 'medium',
    question: 'The Strait of Gibraltar separates Europe from which continent?',
    correct_answer: 'Africa',
    answers: ['Africa', 'Asia', 'South America', 'North America'] },
  { id: 'f-ge-9', category: 'Geography', type: 'multiple', difficulty: 'medium',
    question: 'What is the smallest continent by area?',
    correct_answer: 'Australia',
    answers: ['Australia', 'Europe', 'Antarctica', 'South America'] },
  { id: 'f-ge-10', category: 'Geography', type: 'multiple', difficulty: 'medium',
    question: 'Which ocean is the Indian Ocean bordered by to the east?',
    correct_answer: 'Pacific Ocean',
    answers: ['Pacific Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Southern Ocean'] },
  { id: 'f-ge-11', category: 'Geography', type: 'multiple', difficulty: 'medium',
    question: 'The Amazon rainforest is primarily located in which country?',
    correct_answer: 'Brazil',
    answers: ['Brazil', 'Peru', 'Colombia', 'Venezuela'] },
  { id: 'f-ge-12', category: 'Geography', type: 'multiple', difficulty: 'hard',
    question: 'What is the deepest lake in the world?',
    correct_answer: 'Lake Baikal',
    answers: ['Lake Baikal', 'Lake Tanganyika', 'Caspian Sea', 'Lake Superior'] },
  { id: 'f-ge-13', category: 'Geography', type: 'multiple', difficulty: 'hard',
    question: 'Which country has the most time zones?',
    correct_answer: 'France',
    answers: ['France', 'Russia', 'USA', 'Australia'] },
  { id: 'f-ge-14', category: 'Geography', type: 'multiple', difficulty: 'hard',
    question: 'What is the capital of Kazakhstan?',
    correct_answer: 'Astana',
    answers: ['Astana', 'Almaty', 'Tashkent', 'Bishkek'] },
  { id: 'f-ge-15', category: 'Geography', type: 'multiple', difficulty: 'medium',
    question: 'Which sea lies between Italy and the Balkans?',
    correct_answer: 'Adriatic Sea',
    answers: ['Adriatic Sea', 'Aegean Sea', 'Tyrrhenian Sea', 'Ionian Sea'] },
];

export async function fetchTriviaQuestions(
  count: number = 5,
  categoryId: string = 'mixed',
  difficulty: 'easy' | 'medium' | 'hard' | 'any' = 'any'
): Promise<TriviaQuestion[]> {
  try {
    const catNum = CATEGORY_MAP[categoryId] ?? 0;
    let url = `https://opentdb.com/api.php?amount=${count}&type=multiple`;
    if (catNum > 0) url += `&category=${catNum}`;
    if (difficulty !== 'any') url += `&difficulty=${difficulty}`;

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 8000);

    const res = await fetch(url, { signal: controller.signal });
    clearTimeout(timeout);

    if (!res.ok) throw new Error(`HTTP ${res.status}`);

    const data: OTDBResponse = await res.json();

    if (data.response_code !== 0 || !data.results?.length) {
      throw new Error(`OTDB code ${data.response_code}`);
    }

    return data.results.map((q, i) => ({
      id: `q_${Date.now()}_${i}`,
      category: decodeHTML(q.category),
      type: q.type as 'multiple' | 'boolean',
      difficulty: q.difficulty as 'easy' | 'medium' | 'hard',
      question: decodeHTML(q.question),
      correct_answer: decodeHTML(q.correct_answer),
      answers: shuffleArray([
        decodeHTML(q.correct_answer),
        ...q.incorrect_answers.map(decodeHTML),
      ]),
    }));
  } catch (err) {
    console.warn('[Trivia] API failed, using fallback:', err);
    // Shuffle questions AND shuffle each question's answers — the static
    // bank lists the correct answer first, which would otherwise leak.
    return shuffleArray(FALLBACK_QUESTIONS)
      .slice(0, count)
      .map((q) => ({ ...q, answers: shuffleArray(q.answers) }));
  }
}

// ─── Score Calculation ───────────────────────────────────────────────────────
export interface RoundResult {
  question: TriviaQuestion;
  selectedAnswer: string | null;
  isCorrect: boolean;
  timeTaken: number; // seconds
  pointsEarned: number;
}

export function calculatePoints(
  isCorrect: boolean,
  difficulty: string,
  timeTaken: number,
  roundTimeLimit: number = 15
): number {
  if (!isCorrect) return 0;

  const basePoints: Record<string, number> = { easy: 100, medium: 150, hard: 250 };
  const base = basePoints[difficulty] ?? 150;

  // Speed bonus: up to 50% extra for fast answers
  const timeRatio = Math.max(0, (roundTimeLimit - timeTaken) / roundTimeLimit);
  const speedBonus = Math.floor(base * 0.5 * timeRatio);

  return base + speedBonus;
}

export function calculateXP(score: number, streak: number): number {
  const streakMultiplier = Math.min(1 + streak * 0.1, 2.0); // Max 2x at streak 10
  return Math.floor(score * streakMultiplier * 0.1);
}

export function getLevelFromXP(xp: number): number {
  if (xp <= 0) return 1;
  return Math.floor(Math.sqrt(xp / 50)) + 1;
}

export function getXPForNextLevel(currentLevel: number): number {
  return Math.pow(currentLevel, 2) * 50;
}
